name: Build APK
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Hiển thị để chắc chắn đang dùng file mới
    - name: Debug
      run: |
        pwd; ls -la
        echo "grep InventoryLiteFixed:"; grep -R "InventoryLiteFixed" -n . || true

    # Chuẩn bị project: unzip nếu có file zip ở root, dời source ra root
    - name: Prepare project
      shell: bash
      run: |
        set -euxo pipefail
        ZIP=$(ls -1 *.zip 2>/dev/null | head -n1 || true)
        if [ -n "$ZIP" ]; then unzip -qo "$ZIP"; fi
        CAND=$(find . -maxdepth 2 -type f \( -name settings.gradle -o -name settings.gradle.kts \) -printf '%h\n' | head -n1 || true)
        if [ -n "$CAND" ] && [ "$CAND" != "." ]; then
          shopt -s dotglob; mv "$CAND"/* .; rm -rf "$CAND"
        fi
        test -f settings.gradle -o -f settings.gradle.kts
        test -d app
        ls -la

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - uses: android-actions/setup-android@v3

    - name: Install SDK packages
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

    # Cài Gradle 8.6 thủ công, tránh action setup-gradle gây lệch cwd
    - name: Install Gradle 8.6
      run: |
        curl -L https://services.gradle.org/distributions/gradle-8.6-bin.zip -o gradle.zip
        unzip -q gradle.zip
        echo "$PWD/gradle-8.6/bin" >> $GITHUB_PATH
        gradle -v

    - name: Generate wrapper
      run: gradle wrapper --gradle-version 8.6

    - name: Build debug APK
      run: ./gradlew --no-daemon assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
