name: Build APK
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Detect project dir
      id: detect
      shell: bash
      run: |
        set -euxo pipefail
        ZIP=$(ls -1 *.zip 2>/dev/null | head -n1 || true)
        if [ -n "$ZIP" ]; then unzip -qo "$ZIP"; fi
        PROJ=$(find . -maxdepth 2 -type f \( -name settings.gradle -o -name settings.gradle.kts \) -printf '%h\n' | head -n1)
        echo "PROJECT_DIR=$PROJ" >> "$GITHUB_ENV"
        ls -la "$PROJ"

    # Patch: thêm theme + launcher icons nếu thiếu
    - name: Patch missing Android resources
      shell: bash
      run: |
        set -euxo pipefail
        cd "$PROJECT_DIR"
        mkdir -p app/src/main/res/{values,mipmap-anydpi-v26,drawable}
        # theme
        cat > app/src/main/res/values/themes.xml <<'XML'
        <resources xmlns:tools="http://schemas.android.com/tools">
          <style name="Theme.InventoryLite" parent="Theme.Material3.DayNight.NoActionBar">
            <item name="android:statusBarColor" tools:targetApi="l">@android:color/transparent</item>
          </style>
        </resources>
        XML
        # colors for launcher bg
        cat > app/src/main/res/values/colors.xml <<'XML'
        <resources>
          <color name="ic_launcher_background">#FFFFFF</color>
        </resources>
        XML
        # adaptive icons
        cat > app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml <<'XML'
        <adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
          <background android:drawable="@color/ic_launcher_background"/>
          <foreground android:drawable="@drawable/ic_launcher_foreground"/>
        </adaptive-icon>
        XML
        cp app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
        # simple vector foreground
        cat > app/src/main/res/drawable/ic_launcher_foreground.xml <<'XML'
        <vector xmlns:android="http://schemas.android.com/apk/res/android"
            android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">
          <path android:fillColor="#000000" android:pathData="M20,20h68v68h-68z"/>
          <path android:fillColor="#FFFFFF" android:pathData="M34,54h40v8h-40z"/>
        </vector>
        XML
        echo "Patched resources."

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - uses: android-actions/setup-android@v3

    - name: Install SDK packages
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

    - name: Install Gradle 8.6
      run: |
        curl -L https://services.gradle.org/distributions/gradle-8.6-bin.zip -o gradle.zip
        unzip -q gradle.zip
        echo "$PWD/gradle-8.6/bin" >> $GITHUB_PATH
        gradle -v

    - name: Generate wrapper
      working-directory: ${{ env.PROJECT_DIR }}
      run: gradle wrapper --gradle-version 8.6

    - name: Build debug APK
      working-directory: ${{ env.PROJECT_DIR }}
      run: |
        echo "org.gradle.jvmargs=-Xmx3g -Dkotlin.daemon.jvm.options=-Xmx2g" >> gradle.properties
        ./gradlew --no-daemon --stacktrace --info assembleDebug

    - name: Upload APK
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: ${{ env.PROJECT_DIR }}/app/build/outputs/apk/debug/app-debug.apk

    - name: Upload Gradle logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: gradle-logs
        path: |
          ~/.gradle/daemon/*/daemon-*.log
          ${{ env.PROJECT_DIR }}/**/build/reports/**
