name: Build APK
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Prepare project and detect dir
      shell: bash
      run: |
        set -euxo pipefail
        ls -la
        # Unzip nếu repo chỉ có 1 file zip
        ZIP=$(ls -1 *.zip 2>/dev/null | head -n1 || true)
        if [ -n "$ZIP" ]; then unzip -qo "$ZIP"; fi
        # Tìm thư mục có settings.gradle
        CAND=$(find . -maxdepth 2 -type f \( -name settings.gradle -o -name settings.gradle.kts \) -printf '%h\n' | head -n1 || true)
        if [ -z "$CAND" ]; then echo "Không thấy settings.gradle"; exit 1; fi
        echo "PROJECT_DIR=$CAND" >> "$GITHUB_ENV"
        echo "Project dir: $CAND"
        ls -la "$CAND"

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - uses: android-actions/setup-android@v3

    - name: Install SDK packages
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

    - name: Generate Gradle wrapper 8.6
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: 8.6
        build-root-directory: ${{ env.PROJECT_DIR }}
        arguments: wrapper

    - name: Build debug APK
      uses: gradle/gradle-build-action@v3
      with:
        build-root-directory: ${{ env.PROJECT_DIR }}
        arguments: assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: ${{ env.PROJECT_DIR }}/app/build/outputs/apk/debug/app-debug.apk
